name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - ellisonleao
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: 1,2,3 steps on how to reproduce it
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      value: "It should work as.."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      value: "It should work as.."
    validations:
      required: false
